services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - [ setFramework, [ '@contao.framework' ] ]

    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - [ setContainer, [ '@service_container' ] ]

  caledit.service.auth:
    class: Diversworld\CalendarEditorBundle\Services\CheckAuthService
    autowire: true
    autoconfigure: true
    public: true

  Diversworld\CalendarEditorBundle\:
    resource: ../src/
    exclude: ../src/{DependencyInjection,Model}

  Diversworld\CalendarEditorBundle\Controller\Module\ModuleCalendarEdit:
    calls:
      - [ setCheckAuthService, [ '@caledit.service.auth' ] ]

  Diversworld\CalendarEditorBundle\Controller\Module\ModuleEventEditor:
    arguments:
      - '@?logger'
      - '@contao.security.token_checker'
    tags:
      - { name: monolog.logger, channel: contao.general }

  Diversworld\CalendarEditorBundle\Hooks\ListAllEventsHook:
    arguments:
      $checkAuthService: '@caledit.service.auth'

  monolog.logger.contao.general:
    class: Monolog\Logger
    arguments: [ 'contao.general' ]
    tags:
      - { name: monolog.logger, channel: contao.general }
